name: Provison Infrastructure
run-name: ${{github.actor}}
on: [workflow_dispatch]
jobs:
  DEV-PLAN:
    runs-on: self-hosted
    steps:
      - name: copy code 
        uses: actions/checkout@v4
      - name: Initialise terraform
        run: |
          terraform init -backend-config=env-dev/state.tfvars
      - name: Plan terraform
        run: |
          terraform plan -var-file=env-dev/main.tfvars
  DEV-APPLY:
    runs-on: self-hosted
    needs: DEV-PLAN
    steps:
      - name: copy code 
        uses: actions/checkout@v4
      - name: Initialise terraform
        run: |
          terraform init -backend-config=env-dev/state.tfvars
      - name: Apply terraform
        run: |
          terraform apply -var-file=env-dev/main.tfvars -auto-approve
  QA:
    runs-on: self-hosted
    needs: DEV-APPLY
    steps:
      - name: copy code 
        run: echo dumy QA
  UAT:
    runs-on: self-hosted
    needs: QA
    steps:
      - name: copy code 
        run: echo dumy QA
  PROD:
    runs-on: self-hosted
    needs: UAT
    steps:
      - name: copy code 
        uses: actions/checkout@v4
      - name: Initialise terraform
        run: |
          terraform init -backend-config=env-prod/state.tfvars
      - name: Applye terraform
        run: |
          terraform apply -auto-approve